---
- name: Configure base SSH policy
  when: base_manage_ssh | bool
  ansible.builtin.include_tasks: ssh.yml

- name: Configure base VNC display policy
  when: base_manage_vnc | bool
  ansible.builtin.include_tasks: vnc.yml

- name: Configure base disabled services
  when: base_manage_disabled_services | bool
  ansible.builtin.include_tasks: services.yml

- name: Configure base unattended upgrades
  when: base_manage_unattended_upgrades | bool
  ansible.builtin.include_tasks: unattended-upgrades.yml

- name: Configure base reboot notification
  when: base_manage_reboot_notification | bool
  ansible.builtin.include_tasks: reboot-notification.yml

- name: Configure base cloud-init policy
  when: base_manage_cloud_init | bool
  ansible.builtin.include_tasks: cloud-init.yml
