---
- name: Install shutdown notification helper
  ansible.builtin.template:
    src: piserv-shutdown-notify.py.j2
    dest: "{{ base_shutdown_notification_script_path }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Install shutdown notification service
  ansible.builtin.template:
    src: piserv-shutdown-notify.service.j2
    dest: "/etc/systemd/system/{{ base_shutdown_notification_service_name }}"
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Enable shutdown notification service
  ansible.builtin.systemd_service:
    name: "{{ base_shutdown_notification_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
  become: true
