---
- name: Validate cgroup memory-controller target
  ansible.builtin.import_tasks: validate-target.yml
  when: cgroup_memory_controller_manage | bool

- name: Configure cgroup memory-controller policy
  ansible.builtin.import_tasks: configuration.yml
  when: cgroup_memory_controller_manage | bool
