---
firewall_manage_package: true
firewall_package_name: ufw
firewall_apt_update_cache: true
firewall_apt_cache_valid_time: 3600

firewall_manage_defaults: true
firewall_default_incoming_policy: deny
firewall_default_outgoing_policy: allow
firewall_default_routed_policy: deny

firewall_rules: []

firewall_manage_logging: true
firewall_logging: low

firewall_manage_state: true
firewall_state: enabled
firewall_manage_service: true
firewall_service_name: ufw.service

firewall_validate: true
firewall_supported_os_families:
  - Debian
