---
- name: Validate firewall role inputs
  ansible.builtin.import_tasks: validate-inputs.yml

- name: Install firewall package
  when: firewall_manage_package | bool
  ansible.builtin.import_tasks: packages.yml

- name: Configure firewall policy
  ansible.builtin.import_tasks: policy.yml

- name: Validate firewall runtime state
  when: firewall_validate | bool
  ansible.builtin.import_tasks: validate-runtime.yml
