---
- name: Configure PiServ external storage
  hosts: piserv
  gather_facts: true
  become: true
  tasks:
    - name: Apply external storage policy
      ansible.builtin.include_tasks: ../tasks/external-storage.yml
