---
- name: Validate sshd configuration
  ansible.builtin.command:
    argv:
      - "{{ base_sshd_binary }}"
      - -t
  changed_when: false
  become: true
  listen: Validate and reload sshd

- name: Reload ssh service
  ansible.builtin.systemd_service:
    name: "{{ base_ssh_service_name }}"
    state: reloaded
  become: true
  listen: Validate and reload sshd

- name: Restart Glances service
  ansible.builtin.systemd_service:
    name: "{{ base_glances_service_name }}"
    state: restarted
    daemon_reload: true
  become: true

- name: Restart systemd-journald
  ansible.builtin.systemd_service:
    name: systemd-journald.service
    state: restarted
  become: true
  listen: Restart and flush systemd-journald

- name: Flush system journal to persistent storage
  ansible.builtin.command:
    argv:
      - journalctl
      - --flush
  changed_when: false
  become: true
  listen: Restart and flush systemd-journald
