---
galaxy_info:
  author: Marco Massari Calderone
  description: Install and configure the Home Assistant API CLI.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
dependencies: []
