---
- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Wi-Fi watchdog
  become: true
  ansible.builtin.systemd:
    name: "{{ wifi_watchdog_service_name }}"
    state: restarted
  when: not ansible_check_mode or wifi_watchdog_service_unit.stat.exists
